"""Generate analysis report from pipeline output."""
import json
import os
import sys
from pathlib import Path
from datetime import datetime

output_dir = Path(r"F:\NeuroLens2\outputs\Qwen2.5-1.5B-Instruct\test_snip")

# Load SNIP scores
snip_path = output_dir / "snip_scores" / "snip_scores.json"
with open(snip_path, "r", encoding="utf-8") as f:
    snip = json.load(f)

# Load layer evolution
evo_path = output_dir / "layer_evolution" / "streamgraph_data.json"
with open(evo_path, "r", encoding="utf-8") as f:
    evo = json.load(f)

# Load quadrant classification
quad_path = output_dir / "quadrant_classification.json"
with open(quad_path, "r", encoding="utf-8") as f:
    quad = json.load(f)

# Load safety neurons
safe_path = output_dir / "dedicated_safety_neurons.json"
with open(safe_path, "r", encoding="utf-8") as f:
    safe = json.load(f)

# Compute stats
import numpy as np
scores = [v["snip_score"] for v in snip.values()]
sorted_neurons = sorted(snip.items(), key=lambda x: x[1]["snip_score"], reverse=True)

# Layer distribution
from collections import Counter
layer_counts = Counter(v["layer_idx"] for v in snip.values())

# Best separating layer
best_layer = max(evo, key=lambda x: abs(x["success"]["mean"] - x["fail"]["mean"]))

# Generate report
report = f"""# NeuroLens Analysis Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Model:** Qwen2.5-1.5B-Instruct
**Samples:** 200 (attack_enhanced_set_train.jsonl)
**GPU:** NVIDIA GeForce RTX 4060 Laptop GPU (8GB)

---

## 1. SNIP Score Summary

| Metric | Value |
|--------|-------|
| Total neurons scored | {len(scores):,} |
| Score range | {min(scores):.6f} ~ {max(scores):.6f} |
| Mean | {np.mean(scores):.6f} |
| Median | {np.median(scores):.6f} |
| Std | {np.std(scores):.6f} |

### Top 10 Most Important Neurons (by SNIP score)

| Rank | Neuron | Layer | SNIP Score |
|------|--------|-------|------------|
"""
for i, (k, v) in enumerate(sorted_neurons[:10], 1):
    report += f"| {i} | {k} | L{v['layer_idx']} | {v['snip_score']:.6f} |\n"

report += f"""
### Neurons per Layer (Top 10 layers)

| Layer | Count |
|-------|-------|
"""
for layer, count in sorted(layer_counts.items(), key=lambda x: x[1], reverse=True)[:10]:
    report += f"| L{layer} | {count:,} |\n"

report += f"""
---

## 2. Layer Evolution Analysis

The streamgraph data shows how safety signals evolve across the {len(evo)} transformer layers.

| Metric | Value |
|--------|-------|
| Total layers | {len(evo)} |
| Best separating layer | L{best_layer['layer']} |
| Success mean (L{best_layer['layer']}) | {best_layer['success']['mean']:.6f} |
| Fail mean (L{best_layer['layer']}) | {best_layer['fail']['mean']:.6f} |
| Separation | {abs(best_layer['success']['mean'] - best_layer['fail']['mean']):.6f} |

### Layer-wise Activation Norms (Success vs Fail)

| Layer | Success Mean | Fail Mean | Separation |
|-------|-------------|-----------|------------|
"""
for layer_data in evo[:10]:
    l = layer_data["layer"]
    s = layer_data["success"]["mean"]
    f = layer_data["fail"]["mean"]
    sep = abs(s - f)
    report += f"| L{l} | {s:.4f} | {f:.4f} | {sep:.4f} |\n"
report += "| ... | ... | ... | ... |\n"
for layer_data in evo[-3:]:
    l = layer_data["layer"]
    s = layer_data["success"]["mean"]
    f = layer_data["fail"]["mean"]
    sep = abs(s - f)
    report += f"| L{l} | {s:.4f} | {f:.4f} | {sep:.4f} |\n"

report += f"""
---

## 3. Quadrant Classification

Total classified neurons: {len(quad)}

"""
if quad:
    quad_counts = Counter(v.get("quadrant", "unknown") for v in quad.values())
    report += "| Quadrant | Count | Description |\n|----------|-------|-------------|\n"
    quad_desc = {
        "S+A+": "High safety + High activation (critical safety neurons)",
        "S-A-": "Low safety + Low activation (benign neurons)",
        "S+A-": "High safety + Low activation (safety-only neurons)",
        "S-A+": "Low safety + High activation (activation-only neurons)",
    }
    for q, c in sorted(quad_counts.items()):
        report += f"| {q} | {c:,} | {quad_desc.get(q, 'Unknown')} |\n"

report += f"""
---

## 4. Safety Neurons

Dedicated safety neurons identified: {len(safe.get('neurons', {}))}

---

## 5. Files Generated

| File | Description |
|------|-------------|
| `snip_scores/snip_scores.json` | Full SNIP scores for all {len(scores):,} neurons |
| `layer_evolution/streamgraph_data.json` | Layer-wise activation norms |
| `layer_evolution/semantic_evolution.json` | Semantic evolution data |
| `quadrant_classification.json` | Neuron quadrant classification |
| `dedicated_safety_neurons.json` | Identified safety neurons |
| `assessment/evaluation_results.json` | Full inference results |
| `assessment/summary.json` | ASR and performance summary |

---

*Report generated by NeuroLens Analysis Pipeline*
"""

# Save report
report_path = output_dir / "REPORT.md"
with open(report_path, "w", encoding="utf-8") as f:
    f.write(report)

print(f"Report saved to: {report_path}")
print(f"SNIP scores: {len(scores):,} neurons")
print(f"Top neuron: {sorted_neurons[0][0]} (score={sorted_neurons[0][1]['snip_score']:.6f})")
